import java_cup.runtime.*;

terminal Integer INTEIRO;
terminal MAIS, MENOS, PTVIRG;

non terminal inicio;
non terminal Integer expr;

precedence left MAIS, MENOS;

start with inicio;

inicio ::= expr:e PTVIRG {: System.out.println(e); :}
         ;

expr ::= expr:a MAIS expr:b  {: RESULT = a.intValue() + b.intValue(); :}
       | expr:a MENOS expr:b {: RESULT = a.intValue() - b.intValue(); :}
       | INTEIRO:a           {: RESULT = a.intValue(); :}
       ;
